
#server:
#  port: 8761                    # 指定该Eureka实例的端口

#eureka:
#  instance:
#    hostname: discovery         # 指定该Eureka实例的主机名
 # client:
 #   registerWithEureka: false
 #   fetchRegistry: false
 #   serviceUrl:
  #    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
   application:
    name: eureka-server
security:
  basic:
    enabled: true
  user:
    name: root
    password: root
---
spring:
  profiles: discovery                                 # 指定profile=discovery
server:
  port: 8761
eureka:
  instance:
    hostname: discovery                               # 指定当profile=discovery，主机名
    #virtual-host-name:                   #虚拟主机名(默认和服务名称一致)
  client:
    serviceUrl:
      defaultZone: http://root:root@discovery2:8762/eureka/      # 将自己注册到discovery2这个Eureka上面去
    healthcheck:
      enabled: true

---
spring:
  profiles: discovery2
server:
  port: 8762
eureka:
  instance:
    hostname: discovery2
    #virtual-host-name:
  client:
    serviceUrl:
      defaultZone: http://root:root@discovery:8761/eureka/
    healthcheck:
          enabled: true